name: Bump version

on:
  push:
    branches:
      - master

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump'"
    runs-on: ubuntu-latest
    name: "Commitizen - Increase version and create changelog"

    steps:
      - name: Code check
        uses: actions/checkout@v3
        with:
          token: "${{ secrets.PERSONAL_ACCESS_TOKEN_CZ }}"
          fetch-depth: 0

      - name: Creating a bump and changelog
        id: cz
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN_CZ }}

      - name: View version
        run: echo "Increased to version ${{ steps.cz.outputs.version }}"
      
      - name: Pushing out changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "GitHub Action"
          git push origin master --tags

