name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deepsource:
    runs-on: ubuntu-latest
    env:
      DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha  || github.sha }}
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          
      - name: Build with Maven
        run: |
          mvn clean install

      - name: Run Tests and Generate Coverage
        run: |
          mvn clean test jacoco:report

      - name: Report test coverage to DeepSource
        uses: deepsourcelabs/test-coverage-action@master
        with:
          key: java 
          coverage-file: /reports/jacoco.xml
          dsn: ${{ secrets.DEEPSOURCE_DSN }}

      - name: Run DeepSource analysis
        uses: deepsourcelabs/deepsource-action@master
        with:
          dsn: ${{ secrets.DEEPSOURCE_DSN }}
          
      - name: Upload JaCoCo report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: /reports/jacoco.xml
          