name: CI

on:
  push:
    branches:
      - main

jobs:
  deepsource:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Run tests and generate coverage report
        run: |
          mvn clean test jacoco:report

      - name: Report test coverage to DeepSource
        uses: deepsourcelabs/test-coverage-action@master
        with:
          key: java 
          coverage-file: target/site/jacoco/jacoco.xml
          dsn: ${{ secrets.DEEPSOURCE_DSN }}

      - name: Run DeepSource analysis
        uses: deepsourcelabs/deepsource-action@master
        with:
          dsn: ${{ secrets.DEEPSOURCE_DSN }}
          